source("./SCRIPTS/Librerias.R")
source("./SCRIPTS/limpieza de datos.R")
rm(list=ls())
source("./SCRIPTS/Estadisticos sql en R.R")
rm(list=ls())
source("./SCRIPTS/Estadistica Matematica.R")
rm(list=ls())
source("./SCRIPTS/recomendador empresa.R")
rm(list=ls())
source("./SCRIPTS/Shiny Reto04.R")
rm(list=ls())
source("./SCRIPTS/Data Mining.R")
